# ALGORITHM


# **Linear Regression Algorithm**

### **Step 1: Initialize Parameters**

1. **Input**:

   - Feature matrix \( X \) (input data).
   - Target vector \( Y \) (output data).
   - Set initial parameters (weights) \( \theta \) to random values.

2. **Output**:
   - Initial parameters \( \theta \).

---

### **Step 2: Add Bias Term**

1. **Add a Bias Term**:

   - Augment the feature matrix \( X \) by adding a column of ones to account for the intercept \( \theta_0 \) (bias term).
   - New feature matrix \( X_b \) includes this bias term.

2. **Output**:
   - Augmented feature matrix \( X_b \).

---

### **Step 3: Define Hypothesis Function**

1. **Define the Hypothesis**:

   - The hypothesis function \( h(X) \) is defined as the linear combination of the input features and the parameters:
     \[
     h(X) = X_b \cdot \theta
     \]
   - This predicts the target value \( \hat{Y} \) for a given input \( X_b \).

2. **Output**:
   - Predicted values \( \hat{Y} \).

---

### **Step 4: Define Cost Function**

1. **Define the Cost Function**:

   - Use the Mean Squared Error (MSE) as the cost function to measure the difference between the predicted values \( \hat{Y} \) and the actual values \( Y \):
     \[
     J(\theta) = \frac{1}{2m} \sum\_{i=1}^{m} (h(X^{(i)}) - Y^{(i)})^2
     \]
   - \( m \) is the number of training examples.

2. **Output**:
   - The cost \( J(\theta) \) representing the model’s error.

---

### **Step 5: Implement Gradient Descent**

1. **Iteratively Update Parameters**:

   - For a given number of iterations, update the parameters \( \theta \) using the gradient descent algorithm:
     \[
     \theta = \theta - \alpha \cdot \frac{\partial J(\theta)}{\partial \theta}
     \]
   - Here, \( \alpha \) is the learning rate, and the gradient \( \frac{\partial J(\theta)}{\partial \theta} \) is computed as:
     \[
     \text{Gradient} = \frac{1}{m} X_b^T \cdot (h(X) - Y)
     \]
   - The gradient points in the direction of the steepest increase of the cost function, so subtracting it from \( \theta \) moves the parameters towards the minimum of the cost function.

2. **Output**:
   - Optimized parameters \( \theta \).
   - A history of the cost function value at each iteration (optional).

---

### **Step 6: Train the Model**

1. **Minimize the Cost Function**:

   - Run gradient descent until the cost function converges or reaches a predefined number of iterations.
   - The parameters \( \theta \) that minimize the cost function are considered the optimal model parameters.

2. **Output**:
   - Final optimized parameters \( \theta \).

---

### **Step 7: Make Predictions**

1. **Predict New Values**:

   - Use the optimized parameters \( \theta \) to make predictions on new data:
     \[
     \hat{Y} = X_b \cdot \theta
     \]
   - These predictions \( \hat{Y} \) are the model’s outputs for the given inputs.

2. **Output**:
   - Predicted target values \( \hat{Y} \) for the input features.

---

### **Step 8: Evaluate the Model**

1. **Evaluate the Model’s Performance**:

   - Assess the model by computing the final cost \( J(\theta) \) using the optimized parameters.
   - Optionally, use other metrics such as R-squared, Root Mean Squared Error (RMSE), etc.

2. **Output**:
   - Final cost value \( J(\theta) \).
   - Model parameters \( \theta \) that can be used for further predictions.

---

### **Summary of Algorithm**

1. **Initialize Parameters**: Start with random weights \( \theta \).
2. **Add Bias Term**: Include a bias term in the feature matrix.
3. **Define Hypothesis**: Create a linear model \( h(X) = X_b \cdot \theta \).
4. **Define Cost Function**: Use Mean Squared Error to measure the model’s error.
5. **Gradient Descent**: Iteratively adjust \( \theta \) to minimize the cost function.
6. **Train the Model**: Continue until the cost function converges.
7. **Make Predictions**: Use the final \( \theta \) to predict outcomes for new data.
8. **Evaluate the Model**: Assess the performance using the final cost or other metrics.


# CODE


In [29]:
import numpy as np

In [30]:
X = np.array([[1], [2], [3], [4], [5]])
Y = np.array([3,7,5,11,14])

In [31]:
X_b = np.c_[np.ones((X.shape[0], 1)), X]
theta = np.random.randn(X_b.shape[1], 1)

In [32]:
X_b

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.]])

In [33]:
def predict(X, theta):
    return np.dot(X, theta)

In [34]:
def computeCost(X, Y, theta):
    m = len(Y)
    predictions = predict(X, theta)
    cost = (1 / (2*m)) * np.sum((predictions - Y.reshape(-1, 1)) ** 2)
    return cost

In [35]:
def gradientDescent(X, Y, theta, learningRate, iterations):
    m = len(Y)
    costHistory = np.zeros(iterations)
    
    for i in range(iterations):
        gradients = (1/m) * X.T.dot(predict(X, theta) - Y.reshape(-1,1))
        theta = theta - learningRate * gradients
        costHistory[i] = computeCost(X, Y, theta)
        
    return theta, costHistory

In [36]:
learningRate = 0.01
iterations = 1000

In [37]:
thetaOptimal, costHistory = gradientDescent(X_b, Y, theta, learningRate, iterations)

In [38]:
YPred = predict(X_b, thetaOptimal)
YPred


array([[ 2.94138102],
       [ 5.48721863],
       [ 8.03305624],
       [10.57889385],
       [13.12473147]])

In [39]:
finalCost = computeCost(X_b, Y, thetaOptimal)
finalCost

22.614914137571756

In [40]:
thetaOptimal

array([[0.3955434 ],
       [2.54583761]])

In [41]:
import numpy as np

X = np.array([[1], [2], [3], [4], [5]])
Y = np.array([3,7,5,11,14])

X_b = np.c_[np.ones((X.shape[0], 1)), X]
theta = np.random.randn(X_b.shape[1], 1)

def predict(X, theta):
    return np.dot(X, theta)

def computeCost(X, Y, theta):
    m = len(Y)
    predictions = predict(X, theta)
    cost = (1 / (2*m)) * np.sum((predictions - Y.reshape(-1, 1)) ** 2)
    return cost

def gradientDescent(X, Y, theta, learningRate, iterations):
    m = len(Y)
    costHistory = np.zeros(iterations)
    
    for i in range(iterations):
        gradients = (1/m) * X.T.dot(predict(X, theta) - Y.reshape(-1,1))
        theta = theta - learningRate * gradients
        costHistory[i] = computeCost(X, Y, theta)
        
    return theta, costHistory

learningRate = 0.01
iterations = 1000

thetaOptimal, costHistory = gradientDescent(X_b, Y, theta, learningRate, iterations)

YPred = predict(X_b, thetaOptimal)
print("Predictions: ", YPred)

finalCost = computeCost(X_b, Y, thetaOptimal)
print("Final Cost: ", finalCost)

print("Theta Optimal", thetaOptimal)

Predictions:  [[ 2.79504026]
 [ 5.39694031]
 [ 7.99884037]
 [10.60074042]
 [13.20264047]]
Final Cost:  1.2400042825765334
Theta Optimal [[0.19314021]
 [2.60190005]]
